### 
POST http://localhost:5001/auth/register
Content-Type: application/json

{
  "email": "atmanandacademics@gmail.com",
  "name": "Atmanand Nagpure",
  "password": "changedpass"
}


###

POST http://localhost:5001/auth/activate-account
Content-Type: application/json

{
  "code": "2e1cf82bcf1dcc2fb1dea37b15e8a9347117b904ab462e811fbdafc0418b7217"
}

###


GET http://localhost:5001/auth/

###


POST http://localhost:5001/auth/login
Content-Type: application/json

{
  "login": "atmanandacademics@gmail.com",
  "password": "changedpass"
}

###



GET http://localhost:5001/auth/logout


###
POST http://localhost:5001/test

###

POST http://localhost:5001/auth/forgot-password
Content-Type: application/json

{
  "email": "atmanandacademics@gmail.com"
}


###

POST http://localhost:5001/auth/reset-password
Content-Type: application/json

{
  "code": "7efefbb608d35081956e6b6c3d4e25687316d4632b22d8965f3a54ae24e80358",
  "email": "atmanandacademics@gmail.com",
  "password": "changedpass"
}
